#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main() {
    FILE *fp;
    const char *filename = "src/key_config.vh";
    unsigned char random_byte;

    // Seed the random number generator
    srand(time(NULL));

    // Generate a pseudo-random number between 0 and 255
    random_byte = rand() % 256;

    // Open the file for writing
    fp = fopen(filename, "w");
    if (fp == NULL) {
        printf("Error: Could not open file %s\n", filename);
        return 1;
    }

    // Write the Verilog header content to the file
    fprintf(fp, "// Verilog header for XOR encryption key\n");
    fprintf(fp, "// This file is auto-generated by keygen.c\n\n");
    fprintf(fp, "`define KEY_VALUE 8'h%02X\n", random_byte);

    // Close the file
    fclose(fp);

    printf("Successfully generated new key 0x%02X and updated %s\n", random_byte, filename);

    return 0;
}